# Change of password for all users in vyatta, Even if it is 10-50 devices, it won't make more than 10 mins to change the password across all devices
---
- name: show version and other user level commands
  hosts: all
  gather_facts: false
  connection: local

#Please make sure to have inventory file and all devices are reachable
# Some devices may need more time to save the configuration or to commit it.To avoid this use the below command before running the script
# export ANSIBLE_PERSISTENT_COMMAND_TIMEOUT=300 

  tasks:
    - name: run multiple commands on remote nodes
      vyos_command:
        commands:
        - configure
        - set system login user <username> authentication plaintext-password 'password'
        - commit
        - exit

        
# To execute the file, please run the command "ansible-playbook <playbook_name> -u <usernmame> -k"
#-k is used for the password prompt, enter the password and playbook will be executed                               
          
        
       
      register: print_output

    -  debug: var=print_output.stdout_lines
